# Generated by Django 4.0.3 on 2022-03-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('Tipofamilia', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
