# Generated by Django 4.0.3 on 2022-04-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_rename_tipofamilia_familiar_tipofamilia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
