# Generated by Django 4.0.3 on 2022-04-03 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_familiar_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='tipofamilia',
            new_name='rol_familiar',
        ),
    ]
